title: Prisoner's Dilemma App
description: Documentation for developing and playing the Prisoner's Dilemma game app
theme: just-the-docs

url: https://github.com/randallard/prisoners-dilemma-docs

# Color scheme
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "//github.com/randallard/prisoners-dilemma-docs"

# Footer content
footer_content: "Copyright &copy; 2025 Your Name. Distributed under an MIT license."

# Configure search
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Enable site back to top button
back_to_top: true
back_to_top_text: "Back to top"

# Enable copy button
enable_copy_code_button: true

# Callouts
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
  tip:
    title: Tip
    color: green